### ISSUE TITLE
On-the-fly Spherical Harmonics

### ISSUE THREAD

**Issue by cortner** [ACEsuit/Polynomials4ML.jl#66]
Is there a potential advantage in evaluating spherical harmonics on-the-fly from analytic expressions instead of recursively? It means zero-memory usage. Most likely for large `lmax` no, but we never go that high. And for ENN architectures, one sticks with extremely low degrees. In general, there could be a huge advantage for multi-threading.

An optimized basis code could be code-generated using [StaticPolynomials.jl](https://github.com/JuliaAlgebra/StaticPolynomials.jl)

https://en.wikipedia.org/wiki/Table_of_spherical_harmonics

CC @ilyes319

**Comment by cortner** [comment]
My very first test with just `L = 3`: 
```
# symbolic R-Ylm and using only static arrays
3ns 
# in-place preallocated ... `evaluate!`
107.422 ns
```

**Comment by ilyes319** [comment]
That is very impressive!

How many edges do you have? Do you expect it would get even better as the number of edges increases?

**Comment by cortner** [comment]
this is just a raw micro-benchmark of the Ylm basis. Hard to say how it would affect the performance of the entire architecture

**Comment by cortner** [comment]
@CheukHinHoJerry this might interest you as well...

**Comment by CheukHinHoJerry** [comment]
The speed up is impressive - it would be nice if we have such a version of `Ylm` available. I could do that quickly this weekend. Still, I guess This might not changes a lot since the bottleneck usually comes from the correlation of features from my previous experience.

Would be great if @ilyes319 could let me know about this - is it still the same under some standard hyperparameters in MACE/general graph architectures? Or would the most costly part becomes the embedding after applying tensor contractions and keep the dimension low?

**Comment by cortner** [comment]
Hi Jerry - the bottleneck is different for different models. For some small ACE models that use low correlation order but comparatively large L the Ylms do end up being the bottleneck.

There are also a second aspect here. If we can manage to make this evaluation this fast but on-the-fly without storage (non-trivial!) then might reduce the memory footprint of a GNN in helpful ways.

**Comment by cortner** [comment]
I suggest to not rush into this now. It is not urgent for us, but Ilyes and I briefly discussed it, so I got curious and wanted to try it out.

**Comment by cortner** [comment]
this is superceded by #74
